<?php
/** @var $viewModel Perspective\ErsteViewModule\ViewModel */
/** @var $escaper \Magento\Framework\Escaper */

// Получаем объект ViewModel из блока (предположим, что у вас есть метод getViewModel())
$viewModel = $block->getViewModel();
$title = _('...argc\'Custom" \\ \' < > / =Title');
?>
<h2>Welcome to PerspectiveStudio</h2>

<!-- Выводим результат метода sayHello(), экранируя его содержимое -->
<h3><?= $escaper->escapeHtml($viewModel->sayHello()); ?></h3>

<a href="#" title="<?= $escaper->escapeHtmlAttr($title) ?>">Link</a>

<a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl(route:'customer/account'))); ?>">
    Custom Acount
</a>
